name: Deploy Kong changes to PRD

on:
  push:
    branches:
      - main
    paths:
      - PRD/kong/kong.yaml
      - .github/workflows/deploy-kong-PRD.yaml

jobs:

#  this job is useful to debug workflows, see https://github.com/mheap/debug-artifact
#  debug-artifacts:
#    name: Upload Debug Artifacts
#    runs-on: ubuntu-latest
#    steps:
#      - name: Upload Debug Artifacts
#        uses: mheap/debug-artifact@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-kong:
    name: Deploy Kong to PRD
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: xlpeabrain/setup-deck@v1
        with:
          deck-version: '1.55.0'
          wrapper: false

      - name: Create deck config
        run: |
          echo "skip-workspace-crud: true" > ~/.deck.yaml |
          echo "headers: Kong-Admin-Token:${{ secrets.KONG_ADMIN_TOKEN_DEV }}" >> ~/.deck.yaml |
          echo "kong-addr: ${{ vars.KONG_ADDR_DEV }}" >> ~/.deck.yaml |
          echo "Deck config: " |
          echo "$(cat ~/.deck.yaml)"

      - name: deck sync
        run: |
          deck gateway sync -w ${{ vars.WORKSPACE_FLIGHTS_TEAM }} --select-tag platform-repo-managed \
          PRD/kong/kong.yaml 

