name: Stage Kong changes for PRD in a PR

on:
  push:
    branches:
      - main
      - workflow/**
    paths:
      - platform/kong/.generated/kong.yaml
      - .github/workflows/stage-kong-for-PRD.yaml

jobs:

#  this job is useful to debug workflows, see https://github.com/mheap/debug-artifact
#  debug-artifacts:
#    name: Upload Debug Artifacts
#    runs-on: ubuntu-latest
#    steps:
#      - name: Upload Debug Artifacts
#        uses: mheap/debug-artifact@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  stage-kong-for-prd:
    name: Stage Kong changes for PRD
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
      # forked a version to fix deck setup for mac machines. Original repo: kong/setup-deck@v1
        uses: xlpeabrain/setup-deck@v1
        with:
          deck-version: '1.54.0'
          wrapper: false

      - name: stage combined file for PRD
        run: cp platform/kong/.generated/kong.yaml PRD/kong/kong.yaml

      # Local running is running native, and sharing the same file system
      # create the enviroment variables or .deck.yaml as needed for your setup
      # https://developer.konghq.com/deck/configuration/#environment-variables
      # eg deck.yaml
      # skip-workspace-crud: true
      # headers: Kong-Admin-Token:${{ secrets.KONG_ADMIN_TOKEN }}
      # kong-addr: ${{ var.KONG_ADMIN_URL }} 
      - name: check deck config
        run: |
          echo "Deck config: " |
          echo "$(cat ~/.deck.yaml)"

      - name: deck diff
        id: deck-diff
        # deck diff results in a multi-line output, which requires some
        #  bash gymnastics to handle and pass through to the next job.
        #  See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DIFF<<$EOF" >> $GITHUB_ENV
          deck gateway diff -w ${{ vars.WORKSPACE_FLIGHTS_TEAM }} --select-tag platform-repo-managed PRD/kong/kong.yaml >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Create PR to stage changes for the Kong Gateway in production
        uses: peter-evans/create-pull-request@v5
        with:
          title: "❗PRD❗: Staged changes for Kong Gateway PRD deployment"
          branch: "PRD/kong"
          labels: "PRD,kong"
          body: "Merging this PR will result in the following changes deployed to PRD \n\n ```\n${{env.DIFF}}\n```"

